import React from 'react';
import '../../Styles/layout.css';
import { Link } from 'react-router-dom';
import { useSelector } from 'react-redux';
import {
    FaCheckCircle,
    FaExclamationTriangle,
    FaUserMd,
    FaHeartbeat,
    FaNotesMedical
} from 'react-icons/fa';

const Result = () => {

    const { resultData } = useSelector((state) => state.resultData);

    const hasParkinson = resultData?.toLowerCase().includes('have parkinson');

    return (
        <div className='layout-container result-page'>

            <div className='layout-header'>
                <h1 className='layout-Header'>Parkinson's Prediction</h1>
                <h3 className='layout-subheader'>
                    Your prediction result and health guidance
                </h3>
            </div>

            <div className='result-content'>

                {/* Result Card */}
                <div className={`result-card ${hasParkinson ? 'result-positive' : 'result-negative'}`}>

                    <div className='result-icon'>
                        {hasParkinson
                            ? <FaExclamationTriangle />
                            : <FaCheckCircle />
                        }
                    </div>

                    <p className='result-message'>
                        {resultData || 'Not Yet Evaluated'}
                    </p>

                </div>


                {/* Guidance Section */}
                <div className='guidance-grid'>

                    {/* Healthy Habits */}
                    <div className='guidance-card'>
                        <div className='guidance-icon'>
                            <FaHeartbeat />
                        </div>

                        <h3>Healthy Habits</h3>

                        <ul>
                            <li>Maintain regular physical activity as advised by a professional.</li>
                            <li>Follow a balanced and nutritious diet.</li>
                            <li>Get adequate sleep and maintain a regular sleep schedule.</li>
                            <li>Stay socially and mentally active.</li>
                            <li>Avoid smoking and excessive alcohol consumption.</li>
                        </ul>
                    </div>


                    {/* Specialist Advice */}
                    <div className='guidance-card'>
                        <div className='guidance-icon'>
                            <FaUserMd />
                        </div>

                        <h3>Specialist Consultation</h3>

                        <p>
                            If you have symptoms such as persistent tremors,
                            stiffness, slowed movement, balance problems,
                            changes in handwriting, or changes in speech,
                            consider discussing them with a qualified
                            healthcare professional.
                        </p>
                    </div>


                    {/* Precautions */}
                    <div className='guidance-card'>
                        <div className='guidance-icon'>
                            <FaNotesMedical />
                        </div>

                        <h3>Precautions</h3>

                        <ul>
                            <li>Do not self-diagnose based only on this prediction.</li>
                            <li>Do not start or stop medication without medical advice.</li>
                            <li>Keep track of persistent or worsening symptoms.</li>
                            <li>Share relevant health changes with your doctor.</li>
                            <li>Seek professional evaluation if symptoms continue.</li>
                        </ul>
                    </div>

                </div>


                {/* Important Notice */}
                <div className='medical-notice'>
                    <FaExclamationTriangle />

                    <div>
                        <h3>Important Medical Notice</h3>

                        <p>
                            This result is generated by a machine-learning model
                        based on the provided voice-related measurements.
                            The prediction should not replace examination,
                            diagnosis, or treatment from a qualified medical
                            professional.
                        </p>
                    </div>
                </div>


                {/* Buttons */}
                <div className='result-buttons'>

                    <Link to='/'>
                        <button className='btn'>
                            Home
                        </button>
                    </Link>

                    <Link to='/layout'>
                        <button className='btn'>
                            Try Again
                        </button>
                    </Link>

                </div>

            </div>

        </div>
    );
};

export default Result;